# Generated by Django 4.2.14 on 2024-09-11 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="guest_locker",
            field=models.ForeignKey(
                default=10,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guest_locker_notifications",
                to="api.locker",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notification",
            name="host_locker",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="host_locker_notifications",
                to="api.locker",
            ),
            preserve_default=False,
        ),
    ]
