# Generated by Django 4.2.14 on 2024-09-11 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_notification_guest_locker_notification_host_locker"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="connection_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="api.connectiontype",
            ),
        ),
    ]
