# Generated by Django 4.2.14 on 2024-09-11 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_notification_connection_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="connection_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.connectiontype",
            ),
        ),
    ]
