# Generated by Django 5.0.6 on 2024-09-25 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_notification_connection_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xnode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('validity_until', models.DateTimeField()),
                ('xnode_Type', models.CharField(choices=[('INODE', 'Inode'), ('VNODE', 'Vnode'), ('SNODE', 'Snode')], default='INODE', max_length=50, verbose_name='Xnode Type')),
                ('node_information', models.JSONField(default=dict)),
                ('connection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.connection')),
                ('locker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.locker')),
            ],
        ),
    ]
