# Generated by Django 5.0.6 on 2024-09-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_xnode'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionterms',
            name='purpose',
            field=models.TextField(default=11, max_length=100),
            preserve_default=False,
        ),
    ]
