# Generated by Django 5.0.6 on 2024-10-17 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_xnode_locker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xnode',
            name='connection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.connection'),
        ),
        migrations.AlterField(
            model_name='xnode',
            name='locker',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.locker'),
        ),
    ]
