# Generated by Django 5.0.6 on 2024-10-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_xnode_connection_alter_xnode_locker'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconnectiontypetemplate',
            name='globaltype',
            field=models.CharField(choices=[('template', 'Template'), ('policy', 'Policy')], default='template', max_length=10),
        ),
    ]
