# Generated by Django 5.0.6 on 2024-10-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_globalconnectiontypetemplate_globaltype'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconnectiontypetemplate',
            name='domain',
            field=models.CharField(choices=[('health', 'Health'), ('education', 'Education'), ('finance', 'Finance'), ('personal data', 'Personal Data')], default='personal data', max_length=20),
        ),
    ]
