# Generated by Django 5.0.6 on 2024-10-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_globalconnectiontypetemplate_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalconnectiontypetemplate',
            name='domain',
            field=models.CharField(choices=[('health', 'health'), ('education', 'education'), ('finance', 'finance'), ('personal data', 'personal Data')], default='personal data', max_length=20),
        ),
        migrations.AlterField(
            model_name='globalconnectiontypetemplate',
            name='globaltype',
            field=models.CharField(choices=[('template', 'template'), ('policy', 'policy')], default='template', max_length=10),
        ),
    ]
