# Generated by Django 5.0.6 on 2024-11-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_globalconnectiontypetemplate_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='terms_value_reverse',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='connectionterms',
            name='from_Type',
            field=models.CharField(choices=[('HOST', 'Host'), ('GUEST', 'Guest')], default='GUEST', max_length=50),
        ),
        migrations.AddField(
            model_name='connectionterms',
            name='to_Type',
            field=models.CharField(choices=[('HOST', 'Host'), ('GUEST', 'Guest')], default='HOST', max_length=50),
        ),
    ]
