# Generated by Django 5.0.6 on 2024-11-29 04:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_connection_terms_value_reverse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='upload_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='validity_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 1, 12, 30, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
