# Generated by Django 4.1 on 2024-12-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_connection_closed_resource_upload_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='close_guest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='connection',
            name='close_host',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='connection',
            name='closure_requested_by',
            field=models.CharField(blank=True, choices=[('guest', 'Guest'), ('host', 'Host'), (None, 'Not Initiated')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='validity_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
