# Generated by Django 5.0.6 on 2025-01-07 11:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_connection_close_guest_connection_close_host_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='closure_requested_by',
        ),
        migrations.CreateModel(
            name='TransferHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validity_until', models.DateField(blank=True, null=True)),
                ('transferred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_revoked', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_history', to='api.connection')),
                ('current_locker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_locker_transfers', to='api.locker')),
                ('current_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_transfers', to=settings.AUTH_USER_MODEL)),
                ('previous_locker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_locker_transfers', to='api.locker')),
                ('previous_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_transfers', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_history', to='api.xnode')),
            ],
        ),
    ]
