# Generated by Django 5.0.6 on 2025-01-21 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_connection_closure_requested_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xnode',
            name='forward_provenance',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='xnode',
            name='provenance_stack',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='xnode',
            name='terms',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='Xnode_V2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('validity_until', models.DateTimeField()),
                ('xnode_Type', models.CharField(choices=[('INODE', 'Inode'), ('VNODE', 'Vnode'), ('SNODE', 'Snode')], default='INODE', max_length=50, verbose_name='Xnode Type')),
                ('node_information', models.JSONField(default=dict)),
                ('provenance_stack', models.JSONField(default=dict)),
                ('forward_provenance', models.JSONField(default=dict)),
                ('terms', models.JSONField(default=dict)),
                ('connection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.connection')),
                ('locker', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.locker')),
            ],
        ),
    ]
