# Generated by Django 5.0.6 on 2025-02-12 11:00

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_xnode_forward_provenance_xnode_provenance_stack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectiontype',
            name='permissions',
            field=models.JSONField(default=api.models.get_default_permissions),
        ),
    ]
