# Generated by Django 5.1.4 on 2025-02-13 07:32

import api.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_xnode_forward_provenance_xnode_provenance_stack_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xnode_v2',
            name='forward_provenance',
        ),
        migrations.RemoveField(
            model_name='xnode_v2',
            name='terms',
        ),
        migrations.AddField(
            model_name='xnode_v2',
            name='creator',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xnode_v2',
            name='post_conditions',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='xnode_v2',
            name='snode_list',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='xnode_v2',
            name='vnode_list',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='xnode_v2',
            name='validity_until',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 27, 7, 31, 51, 479177, tzinfo=datetime.timezone.utc)),
        ),
    ]
