# Generated by Django 5.1.4 on 2025-02-16 10:37

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_xnode_v2_forward_provenance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectiontype',
            name='post_conditions',
            field=models.JSONField(default=api.models.get_default_permissions, null=True),
        ),
        migrations.AlterField(
            model_name='xnode_v2',
            name='validity_until',
            field=models.DateTimeField(),
        ),
    ]
