# Generated by Django 5.1.4 on 2025-02-16 10:38

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_connectiontype_post_conditions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectiontype',
            name='post_conditions',
            field=models.JSONField(default=api.models.get_default_permissions),
        ),
    ]
