# Generated by Django 5.0.6 on 2025-02-16 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_connectiontype_permissions'),
        ('api', '0023_alter_connectiontype_post_conditions'),
    ]

    operations = [
    ]
