# Generated by Django 5.0.6 on 2025-02-16 11:49

import api.model.xnode_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_merge_20250216_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectiontype',
            name='permissions',
        ),
        migrations.AlterField(
            model_name='xnode_v2',
            name='post_conditions',
            field=models.JSONField(default=api.model.xnode_model.get_default_post_conditions),
        ),
    ]
