# Generated by Django 5.0.6 on 2025-02-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_connectiontype_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xnode_v2',
            name='provenance_stack',
            field=models.JSONField(default=list),
        ),
    ]
