# Generated by Django 5.0.6 on 2025-03-26 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_notification_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferhistory',
            name='connection',
        ),
        migrations.RemoveField(
            model_name='transferhistory',
            name='current_locker',
        ),
        migrations.RemoveField(
            model_name='transferhistory',
            name='current_owner',
        ),
        migrations.RemoveField(
            model_name='transferhistory',
            name='previous_locker',
        ),
        migrations.RemoveField(
            model_name='transferhistory',
            name='previous_owner',
        ),
        migrations.RemoveField(
            model_name='transferhistory',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='vnode',
            name='connection',
        ),
        migrations.RemoveField(
            model_name='vnode',
            name='guest_locker',
        ),
        migrations.RemoveField(
            model_name='vnode',
            name='host_locker',
        ),
        migrations.RemoveField(
            model_name='vnode',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='xnode',
            name='connection',
        ),
        migrations.RemoveField(
            model_name='xnode',
            name='locker',
        ),
        migrations.DeleteModel(
            name='Snode',
        ),
        migrations.DeleteModel(
            name='TransferHistory',
        ),
        migrations.DeleteModel(
            name='Vnode',
        ),
        migrations.DeleteModel(
            name='Xnode',
        ),
    ]
