# Generated by Django 5.1.4 on 2025-03-28 05:18

import api.model.connection_type_model
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_transferhistory_connection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectiontype',
            name='owner_locker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectiontype_owner_locker', to='api.locker'),
        ),
        migrations.AlterField(
            model_name='connectiontype',
            name='owner_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectiontype_owner_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ConnectionType_V2',
            fields=[
                ('connection_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('connection_type_name', models.CharField(max_length=50)),
                ('connection_description', models.TextField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('validity_time', models.DateTimeField(default=api.model.connection_type_model.default_validity_time)),
                ('post_conditions', models.JSONField(default=api.model.connection_type_model.get_default_permissions)),
                ('owner_locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_locker', to='api.locker')),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
