# Generated by Django 5.1.4 on 2025-03-28 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_connectiontype_owner_locker_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConnectionType_V2',
        ),
    ]
