# Generated by Django 5.0.6 on 2025-04-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_delete_connectiontype_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='xnode_v2',
            name='is_downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
