# Generated by Django 5.0.6 on 2025-04-10 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_xnode_v2_is_downloaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xnode_v2',
            name='is_downloaded',
        ),
    ]
