# Generated by Django 5.0.6 on 2025-04-16 12:12

import api.model.xnode_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_xnode_v2_is_downloaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='xnode_v2',
            name='is_locked',
            field=models.JSONField(default=api.model.xnode_model.get_default_is_locked),
        ),
    ]
