# Generated by Django 5.1.4 on 2025-04-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_xnode_v2_is_locked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='closed',
        ),
        migrations.AddField(
            model_name='connection',
            name='connection_status',
            field=models.CharField(choices=[('established', 'Established'), ('live', 'Live'), ('closed', 'Closed')], default='established', max_length=20),
        ),
    ]
