# Generated by Django 5.1.4 on 2025-04-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_remove_connection_closed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xnode_v2',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=20),
        ),
    ]
