# Generated by Django 5.0.6 on 2025-06-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_notification_extra_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='connection_status',
            field=models.CharField(choices=[('established', 'Established'), ('live', 'Live'), ('closed', 'Closed'), ('revoked', 'Revoked')], default='established', max_length=20),
        ),
    ]
