# Generated by Django 5.0.6 on 2025-06-26 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_connection_connection_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollateralRevertRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xnode_id_snapshot', models.IntegerField(blank=True, null=True)),
                ('original_requested_xnode_id_snapshot', models.IntegerField(blank=True, null=True)),
                ('host_revert', models.BooleanField(default=False)),
                ('guest_revert', models.BooleanField(default=False)),
                ('reverted', models.BooleanField(default=False)),
                ('revert_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.connection')),
                ('original_requested_xnode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_revert_requests', to='api.xnode_v2')),
                ('xnode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revert_requests', to='api.xnode_v2')),
            ],
        ),
    ]
