# Generated by Django 5.0.6 on 2025-07-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_collateralrevertrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='xnode_v2',
            name='guest_revert_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='xnode_v2',
            name='host_revert_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='xnode_v2',
            name='revert_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xnode_v2',
            name='reverted',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='CollateralRevertRequest',
        ),
    ]
