# Generated by Django 5.0.6 on 2025-07-21 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_xnode_v2_guest_revert_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xnode_v2',
            name='revert_reason',
        ),
    ]
