# Generated by Django 5.0.6 on 2025-08-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
    ]
