# Generated by Django 5.0.6 on 2025-08-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_customuser_is_profile_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='login_method',
            field=models.CharField(choices=[('manual', 'Manual'), ('google', 'Google')], default='manual', max_length=10),
        ),
    ]
