# Generated by Django 5.0.6 on 2025-10-06 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_resource_drive_file_name_resource_drive_mime_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='google_refresh_token',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='drive_file_name',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='drive_mime_type',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='drive_owner_email',
        ),
    ]
