# Generated by Django 5.0.6 on 2025-10-07 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_remove_customuser_google_refresh_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=512, verbose_name='Current Access Token')),
                ('refresh_token', models.CharField(blank=True, max_length=512, null=True, verbose_name='Refresh Token')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Access Token Expires At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Google Auth Token',
                'verbose_name_plural': 'Google Auth Tokens',
            },
        ),
    ]
