# Generated by Django 5.0.6 on 2025-10-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_googleauthtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='drive_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='drive_mime_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='drive_owner_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
