# Generated by Django 5.0.6 on 2025-10-30 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_resource_drive_file_name_resource_drive_mime_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleauthtoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 10, 30, 7, 12, 17, 989439, tzinfo=datetime.timezone.utc), verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='googleauthtoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='googleauthtoken',
            name='access_token',
            field=models.TextField(verbose_name='Current Access Token'),
        ),
        migrations.AlterField(
            model_name='googleauthtoken',
            name='refresh_token',
            field=models.TextField(blank=True, null=True, verbose_name='Refresh Token'),
        ),
        migrations.AlterModelTable(
            name='googleauthtoken',
            table='google_auth_tokens',
        ),
    ]
