# Generated by Django 5.0.6 on 2026-01-19 06:02

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_googleauthtoken_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='validity_time',
            field=models.DateTimeField(blank=True, default=api.models.default_validity_time, null=True),
        ),
    ]
