# Generated by Django 5.0.6 on 2024-07-02 06:09

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionType',
            fields=[
                ('connection_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('connection_type_name', models.CharField(max_length=50)),
                ('connection_description', models.TextField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('validity_time', models.DateTimeField(default=api.models.default_validity_time)),
            ],
        ),
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('locker_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(default=None, max_length=200)),
                ('username', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionTerms',
            fields=[
                ('terms_id', models.AutoField(primary_key=True, serialize=False)),
                ('modality', models.CharField(choices=[('obligatory', 'Obligatory'), ('permissive', 'Permissive'), ('forbidden', 'Forbidden')], max_length=50)),
                ('data_element_name', models.CharField(max_length=50)),
                ('data_type', models.CharField(max_length=50)),
                ('sharing_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('conn_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.connectiontype')),
            ],
        ),
        migrations.AddField(
            model_name='connectiontype',
            name='owner_locker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_locker', to='api.locker'),
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('connection_id', models.AutoField(primary_key=True, serialize=False)),
                ('connection_name', models.CharField(max_length=100)),
                ('connection_description', models.TextField(blank=True, null=True)),
                ('requester_consent', models.BooleanField(default=False)),
                ('revoke_source', models.BooleanField(default=False)),
                ('revoke_target', models.BooleanField(default=False)),
                ('validity_time', models.DateTimeField(default=api.models.default_validity_time)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('connection_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_type', to='api.connectiontype')),
                ('source_locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_locker', to='api.locker')),
                ('target_locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_locker', to='api.locker')),
                ('source_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_user', to='api.user')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_user', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('resource_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=50)),
                ('i_node_pointer', models.CharField(default='none', max_length=255)),
                ('version', models.CharField(default='none', max_length=20)),
                ('type', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=7)),
                ('connections', models.ManyToManyField(related_name='connection', to='api.connection')),
                ('locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.locker')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Snode',
            fields=[
                ('snode_id', models.AutoField(primary_key=True, serialize=False)),
                ('operator_constraints', models.JSONField(default=dict)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.resource')),
                ('source_locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snode_source_locker', to='api.locker')),
                ('target_locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snode_target_locker', to='api.locker')),
            ],
        ),
        migrations.AddField(
            model_name='locker',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AddField(
            model_name='connectiontype',
            name='owner_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_user', to='api.user'),
        ),
        migrations.CreateModel(
            name='Vnode',
            fields=[
                ('vnode_id', models.AutoField(primary_key=True, serialize=False)),
                ('operator_constraints', models.JSONField(default=dict)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.connection')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.resource')),
                ('source_locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vnode_source_locker', to='api.locker')),
                ('target_locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vnode_target_locker', to='api.locker')),
            ],
        ),
    ]
