# Generated by Django 5.0.6 on 2024-07-01 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('locker_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(default=None, max_length=200)),
                ('username', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Connection_type',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('validity', models.CharField(max_length=30)),
                ('created', models.CharField(max_length=30)),
                ('locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_type_locker', to='api.locker')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_type_owner', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('connection_id', models.AutoField(primary_key=True, serialize=False)),
                ('connection_name', models.CharField(max_length=100)),
                ('conn_desc', models.CharField(max_length=100)),
                ('requester_consent', models.BooleanField(default=True)),
                ('revoke1', models.BooleanField(default=True)),
                ('revoke2', models.BooleanField(default=True)),
                ('validity', models.CharField(default=None, max_length=30)),
                ('created', models.CharField(default=None, max_length=30)),
                ('conn_type_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='connection_type', to='api.connection_type')),
                ('source_locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_locker', to='api.locker')),
                ('target_locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_locker', to='api.locker')),
                ('source_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_user', to='api.user')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_user', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('resource_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=50)),
                ('i_node_pointer', models.CharField(default='none', max_length=255)),
                ('version', models.CharField(default='none', max_length=20)),
                ('type', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=7)),
                ('connections', models.ManyToManyField(related_name='connection', to='api.connection')),
                ('locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.locker')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.AddField(
            model_name='locker',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
