# Generated by Django 5.0.6 on 2024-06-11 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('agreement_id', models.AutoField(primary_key=True, serialize=False)),
                ('agreement_text', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('locker_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('connection_id', models.AutoField(primary_key=True, serialize=False)),
                ('connection_name', models.CharField(max_length=100)),
                ('access_norm', models.JSONField()),
                ('access_token', models.CharField(default=None, max_length=20, unique=True)),
                ('connection_norm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.agreement')),
                ('source_locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_locker', to='api.locker')),
                ('target_locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_locker', to='api.locker')),
                ('source_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_user', to='api.user')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_user', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('resource_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=50)),
                ('i_node_pointer', models.CharField(default='none', max_length=20)),
                ('version', models.CharField(default='none', max_length=20)),
                ('type', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=7)),
                ('connections', models.ManyToManyField(related_name='connection', to='api.connection')),
                ('locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.locker')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Snode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snode_name', models.CharField(default='test', max_length=30)),
                ('operator_constraints', models.JSONField()),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.resource')),
                ('source_locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snode_source_locker', to='api.locker')),
                ('target_locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snode_target_locker', to='api.locker')),
            ],
        ),
        migrations.AddField(
            model_name='locker',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='signee1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signee1', to='api.user'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='signee2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signee2', to='api.user'),
        ),
        migrations.CreateModel(
            name='Vnode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vnode_name', models.CharField(default='test', max_length=30)),
                ('operator_constraints', models.JSONField()),
                ('connection', models.ManyToManyField(related_name='vnode_connection', to='api.connection')),
                ('resource_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.resource')),
                ('source_locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vnode_source_locker', to='api.locker')),
                ('target_locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vnode_target_locker', to='api.locker')),
            ],
        ),
    ]
