# Generated by Django 5.0.6 on 2024-07-11 10:36

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(default=None, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConnectionType',
            fields=[
                ('connection_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('connection_type_name', models.CharField(max_length=50)),
                ('connection_description', models.TextField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('validity_time', models.DateTimeField(default=api.models.default_validity_time)),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionTerms',
            fields=[
                ('terms_id', models.AutoField(primary_key=True, serialize=False)),
                ('modality', models.CharField(choices=[('obligatory', 'Obligatory'), ('permissive', 'Permissive'), ('forbidden', 'Forbidden')], max_length=50)),
                ('data_element_name', models.CharField(max_length=50)),
                ('data_type', models.CharField(max_length=50)),
                ('sharing_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('conn_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.connectiontype')),
            ],
        ),
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('locker_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='connectiontype',
            name='owner_locker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_locker', to='api.locker'),
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('connection_id', models.AutoField(primary_key=True, serialize=False)),
                ('connection_name', models.CharField(max_length=100)),
                ('connection_description', models.TextField(blank=True, null=True)),
                ('requester_consent', models.BooleanField(default=False)),
                ('revoke_host', models.BooleanField(default=False)),
                ('revoke_guest', models.BooleanField(default=False)),
                ('validity_time', models.DateTimeField(default=api.models.default_validity_time)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('guest_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_user', to=settings.AUTH_USER_MODEL)),
                ('host_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_user', to=settings.AUTH_USER_MODEL)),
                ('connection_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_type', to='api.connectiontype')),
                ('guest_locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_locker', to='api.locker')),
                ('host_locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_locker', to='api.locker')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('resource_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=50)),
                ('i_node_pointer', models.CharField(default='none', max_length=255)),
                ('version', models.CharField(default='none', max_length=20)),
                ('type', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=7)),
                ('connections', models.ManyToManyField(related_name='connection', to='api.connection')),
                ('locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.locker')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Snode',
            fields=[
                ('snode_id', models.AutoField(primary_key=True, serialize=False)),
                ('operator_constraints', models.JSONField(default=dict)),
                ('guest_locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snode_guest_locker', to='api.locker')),
                ('host_locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snode_host_locker', to='api.locker')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.resource')),
            ],
        ),
        migrations.CreateModel(
            name='Vnode',
            fields=[
                ('vnode_id', models.AutoField(primary_key=True, serialize=False)),
                ('operator_constraints', models.JSONField(default=dict)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.connection')),
                ('guest_locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vnode_guest_locker', to='api.locker')),
                ('host_locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vnode_host_locker', to='api.locker')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.resource')),
            ],
        ),
    ]
