# Generated by Django 4.1 on 2024-07-11 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='target_locker',
            new_name='guest_locker',
        ),
        migrations.RenameField(
            model_name='connection',
            old_name='target_user',
            new_name='guest_user',
        ),
        migrations.RenameField(
            model_name='connection',
            old_name='source_locker',
            new_name='host_locker',
        ),
        migrations.RenameField(
            model_name='connection',
            old_name='source_user',
            new_name='host_user',
        ),
    ]
