# Generated by Django 4.1 on 2024-07-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='is_frozen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='connection',
            name='resources',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='connection',
            name='terms_value',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='connectionterms',
            name='host_permissions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('system_admin', 'System Admin'), ('moderator', 'Moderator'), ('user', 'User')], default='user', max_length=20),
        ),
        migrations.AddField(
            model_name='locker',
            name='is_frozen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='connectionterms',
            name='modality',
            field=models.CharField(choices=[('obligatory', 'Obligatory'), ('permissive', 'Permissive'), ('forbidden', 'Forbidden')], default='obligatory', max_length=50),
        ),
    ]
