# Generated by Django 5.0.6 on 2024-06-25 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='access_norm',
        ),
    ]
