# Generated by Django 5.0.6 on 2024-06-17 05:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locker',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
