# Generated by Django 5.0.6 on 2024-06-20 09:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='consent1',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='consent2',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='created',
            field=models.DateTimeField(default=None, verbose_name=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='agreement',
            name='revoke1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agreement',
            name='revoke2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agreement',
            name='validity',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
