# Generated by Django 5.0.6 on 2024-06-25 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_connection_access_norm'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='access_norm',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='access_norm', to='api.agreement'),
        ),
    ]
