# Generated by Django 4.1 on 2024-07-29 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_connection_is_frozen_connection_resources_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='connection_type_id',
            new_name='connection_type',
        ),
    ]
