# Generated by Django 5.0.6 on 2024-06-20 09:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_agreement_consent1_agreement_consent2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
