# Generated by Django 5.0.6 on 2024-06-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_locker_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='locker',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
