# Generated by Django 5.0.6 on 2024-06-24 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_agreement_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='access_norm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_norm', to='api.agreement'),
        ),
    ]
