# Generated by Django 5.0.6 on 2024-08-08 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_connection_type_id_connection_connection_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConnectionTypeTemplate',
            fields=[
                ('connection_type_template_id', models.AutoField(primary_key=True, serialize=False)),
                ('connection_type_name', models.CharField(default='Test type name', max_length=200, unique=True)),
                ('connection_type_description', models.CharField(default='test type description', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='connectionterms',
            name='conn_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.connectiontype'),
        ),
        migrations.CreateModel(
            name='ConnectionTypeRegulationLinkTable',
            fields=[
                ('link_Id', models.AutoField(primary_key=True, serialize=False)),
                ('connection_Type_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.connectiontype')),
                ('conection_Template_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.globalconnectiontypetemplate')),
            ],
        ),
        migrations.AddField(
            model_name='connectionterms',
            name='global_conn_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.globalconnectiontypetemplate'),
        ),
    ]
