# Generated by Django 5.0.6 on 2024-06-19 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_description'),
        ('api', '0003_locker_description'),
    ]

    operations = [
    ]
