# Generated by Django 5.0.6 on 2024-06-22 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge_0002_user_description_0003_locker_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locker',
            name='creation_date',
        ),
    ]
