# Generated by Django 5.0.6 on 2024-08-08 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_globalconnectiontypetemplate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connectiontyperegulationlinktable',
            old_name='connection_Type_Id',
            new_name='connection_type_id',
        ),
        migrations.RenameField(
            model_name='connectiontyperegulationlinktable',
            old_name='conection_Template_Id',
            new_name='global_connection_template_id',
        ),
        migrations.RenameField(
            model_name='connectiontyperegulationlinktable',
            old_name='link_Id',
            new_name='link_id',
        ),
        migrations.RenameField(
            model_name='globalconnectiontypetemplate',
            old_name='connection_type_description',
            new_name='global_connection_type_description',
        ),
        migrations.RenameField(
            model_name='globalconnectiontypetemplate',
            old_name='connection_type_name',
            new_name='global_connection_type_name',
        ),
        migrations.RenameField(
            model_name='globalconnectiontypetemplate',
            old_name='connection_type_template_id',
            new_name='global_connection_type_template_id',
        ),
    ]
