# Generated by Django 5.0.6 on 2024-08-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_connection_type_id_connectiontyperegulationlinktable_connection_type_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalconnectiontypetemplate',
            name='global_connection_type_description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='globalconnectiontypetemplate',
            name='global_connection_type_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
